name: CI Angular app through Github Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./user-manager-backend
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      -
        name: Build with mvn
        run: mvn clean install
      -
        name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: sjaghori
          password: ${{ secrets.USR_MANAGER_GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0
      -
        name: Build and push
        uses: docker/build-push-action@2
        with:
          context: .
          file: ./user-management-backend/Dockerfile
          push: true
          tags: user-management:latest

