name: CI Spring app through Github Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./user-manager-backend
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      -
        name: Build with mvn
        run: mvn -P clean install
      -
        name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: sjaghori
          password: ${{ secrets.USR_MANAGER_GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./user-manager-backend
          push: true
          tags: ghcr.io/sjaghori/user-management:latest

